name: UnnamedRebalance
version: 1.0.5
main: com.unnamedrebalance.UnnamedRebalance.UnnamedRebalance
api-version: '1.21'
author: dezertman1
description: Custom gameplay modifications

commands:
  withdraw:
    description: Trade your max health for a Heart Container item
    usage: /withdraw [hearts]
    aliases: [wd, tradeheart]
  resethealth:
    description: Reset a player's max health to default (10 hearts)
    usage: /resethealth [player]
    permission: unnamedrebalance.resethealth
    aliases: [rh]

permissions:
  unnamedrebalance.resethealth:
    description: Allows resetting player health
    default: op
